import Head from 'next/head'
import Box from '@mui/material/Box'

const Home = () => {
  return (
    <>
      <Head>
        <title>Address book</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box sx={{ padding: 2 }}>Lorem ipsum...</Box>
      </main>
    </>
  )
}

export default Home
